### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by igor-gp** [WP-for-Church/Sermon-Manager#6] opened 2017-03-07 23:17 UTC
`This is mixed feedback for the free version and future paid versions`

I’ve not used User Role Editor, but as long as you set up WP-standard roles/capabilities, that should work with any plugin that does things the normal method.

One other request: rework the UI for the custom taxonomies sermon series, topics, and preachers (also perhaps store the data in wp_termmeta instead of in a single options field? that should improve performance and allow other uses down the road—custom og:image metadata for sermons in a series, etc.).

**Comment by nikola3244** [comment] 2017-03-08 09:26
This will happen in future new version. I don't want to change data structure in old version at all. Not to mention that it will take a long time, but also, we will probably introduce a lot of bugs.

**Comment by igor-gp** [comment] 2017-03-08 09:34
Yeah for sure. Just a placeholder. 

This stuff can be done now however

`I’ve not used User Role Editor, but as long as you set up WP-standard roles/capabilities, that should work with any plugin that does things the normal method.`

**Comment by nikola3244** [comment] 2017-03-09 08:26
#3 is a duplicate of this one. closing.

**Closed by nikola3244** 2017-03-09 08:26 UTC
Labels: duplicate, enhancement
