### ISSUE TITLE
HTTP 500 when importing Sermon Browser content

### ISSUE THREAD

**Issue by yusufk** [WP-for-Church/Sermon-Manager#156] opened 2018-01-08 06:26 UTC
Hi,

I get an http 500 error whenever I try importing Sermon Browser content. Any ideas?

Regards,
Y

**Comment by nikola3244** [comment] 2018-01-08 17:35
Hi, can you please check server error_log file and/or post it here? 
There will be more detailed information about _what_ and _why_ failed.

**Comment by yusufk** [comment] 2018-01-15 04:10
I haven't been able to see anything in the logs unfortunately. It looks like part of the data was imported, Preachers etc. but not actual Sermons. Is it because they're all part of series?

**Comment by nikola3244** [comment] 2018-10-09 06:41
Hi @yusufk,

Apologies for the delay. 

If you are still interested, you could try doing import again, we applied some fixes to importing from Sermon Browser, which are directly related to this issue.

I will close the issue, since one user confirmed that the fixes are working, but feel free to reopen it if the issues are still present. 

Thank you!

**Closed by nikola3244** 2018-10-09 06:41 UTC
Labels: [Blocker] Cannot reproduce, [Blocker] More Info Needed, [Priority] Standard, [Type] Bug, [Type] Question

**Comment by yusufk** [comment] 2018-10-09 08:06
Thank you, you may close.
